"""name=raw_ingestion_tables

Revision ID: 351ece0cc2cf
Revises: 294f76baacc3
Create Date: 2026-06-07 13:23:42.189338

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '351ece0cc2cf'
down_revision: Union[str, None] = '294f76baacc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_internal_txs',
    sa.Column('value', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.Column('chain', sa.String(length=32), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("chain IN ('lemonchain','bsc')", name='ck_raw_internal_txs_chain'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_id', 'tx_hash', 'trace_id', name='uq_raw_internal_txs_wallet_tx_trace')
    )
    op.create_index('ix_raw_internal_txs_wallet_block', 'raw_internal_txs', ['wallet_id', 'block_number'], unique=False)
    op.create_index(op.f('ix_raw_internal_txs_wallet_id'), 'raw_internal_txs', ['wallet_id'], unique=False)
    op.create_table('raw_logs',
    sa.Column('log_index', sa.Integer(), nullable=False),
    sa.Column('contract_address', sa.String(length=42), nullable=False),
    sa.Column('topic0', sa.String(length=66), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.Column('chain', sa.String(length=32), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("chain IN ('lemonchain','bsc')", name='ck_raw_logs_chain'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_id', 'tx_hash', 'log_index', name='uq_raw_logs_wallet_tx_log')
    )
    op.create_index(op.f('ix_raw_logs_contract_address'), 'raw_logs', ['contract_address'], unique=False)
    op.create_index(op.f('ix_raw_logs_topic0'), 'raw_logs', ['topic0'], unique=False)
    op.create_index('ix_raw_logs_wallet_block', 'raw_logs', ['wallet_id', 'block_number'], unique=False)
    op.create_index(op.f('ix_raw_logs_wallet_id'), 'raw_logs', ['wallet_id'], unique=False)
    op.create_table('raw_token_transfers',
    sa.Column('value', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('log_index', sa.Integer(), nullable=False),
    sa.Column('contract_address', sa.String(length=42), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.Column('chain', sa.String(length=32), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("chain IN ('lemonchain','bsc')", name='ck_raw_token_transfers_chain'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_id', 'tx_hash', 'log_index', name='uq_raw_token_transfers_wallet_tx_log')
    )
    op.create_index(op.f('ix_raw_token_transfers_contract_address'), 'raw_token_transfers', ['contract_address'], unique=False)
    op.create_index('ix_raw_token_transfers_wallet_block', 'raw_token_transfers', ['wallet_id', 'block_number'], unique=False)
    op.create_index(op.f('ix_raw_token_transfers_wallet_id'), 'raw_token_transfers', ['wallet_id'], unique=False)
    op.create_table('raw_transactions',
    sa.Column('value', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.Column('chain', sa.String(length=32), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("chain IN ('lemonchain','bsc')", name='ck_raw_transactions_chain'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_id', 'tx_hash', name='uq_raw_transactions_wallet_tx')
    )
    op.create_index('ix_raw_transactions_wallet_block', 'raw_transactions', ['wallet_id', 'block_number'], unique=False)
    op.create_index(op.f('ix_raw_transactions_wallet_id'), 'raw_transactions', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_transactions_wallet_id'), table_name='raw_transactions')
    op.drop_index('ix_raw_transactions_wallet_block', table_name='raw_transactions')
    op.drop_table('raw_transactions')
    op.drop_index(op.f('ix_raw_token_transfers_wallet_id'), table_name='raw_token_transfers')
    op.drop_index('ix_raw_token_transfers_wallet_block', table_name='raw_token_transfers')
    op.drop_index(op.f('ix_raw_token_transfers_contract_address'), table_name='raw_token_transfers')
    op.drop_table('raw_token_transfers')
    op.drop_index(op.f('ix_raw_logs_wallet_id'), table_name='raw_logs')
    op.drop_index('ix_raw_logs_wallet_block', table_name='raw_logs')
    op.drop_index(op.f('ix_raw_logs_topic0'), table_name='raw_logs')
    op.drop_index(op.f('ix_raw_logs_contract_address'), table_name='raw_logs')
    op.drop_table('raw_logs')
    op.drop_index(op.f('ix_raw_internal_txs_wallet_id'), table_name='raw_internal_txs')
    op.drop_index('ix_raw_internal_txs_wallet_block', table_name='raw_internal_txs')
    op.drop_table('raw_internal_txs')
    # ### end Alembic commands ###
