"""name=initial_schema

Revision ID: 294f76baacc3
Revises:
Create Date: 2026-06-05 22:12:37.028517

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "294f76baacc3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_registry",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chain", sa.Text(), nullable=False),
        sa.Column("contract_address", sa.Text(), nullable=True),
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("decimals", sa.SmallInteger(), nullable=False),
        sa.Column("tier", sa.SmallInteger(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("pricing_source_primary", sa.Text(), nullable=True),
        sa.Column("pricing_source_fallback", sa.Text(), nullable=True),
        sa.Column("is_deflationary", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("max_supply", sa.Numeric(), nullable=True),
        sa.Column(
            "project_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('ecosystem-l2','ecosystem-stablecoin','ecosystem-native','external-stablecoin','external-major','external-other')",
            name="ck_token_registry_category",
        ),
        sa.CheckConstraint("chain IN ('lemonchain','bsc')", name="ck_token_registry_chain"),
        sa.CheckConstraint("tier IN (1,2)", name="ck_token_registry_tier"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chain", "contract_address", name="uq_token_registry_chain_address"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("clerk_user_id", sa.Text(), nullable=False),
        sa.Column(
            "preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clerk_user_id"),
    )
    op.create_table(
        "entities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("tax_id", sa.Text(), nullable=True),
        sa.Column("formation_date", sa.Date(), nullable=True),
        sa.Column("fiscal_year_end", sa.Text(), nullable=True),
        sa.Column("default_basis_method", sa.Text(), server_default="fifo", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "default_basis_method IN ('fifo','hifo','specific-id')",
            name="ck_entities_default_basis_method",
        ),
        sa.CheckConstraint(
            "type IN ('personal','s-corp','llc-passthrough','partnership','sole-prop')",
            name="ck_entities_type",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_token_classifications",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_id", sa.Uuid(), nullable=False),
        sa.Column("classification", sa.Text(), server_default="pending-review", nullable=False),
        sa.Column(
            "classified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "classification IN ('include','spam','pending-review')", name="ck_utc_classification"
        ),
        sa.ForeignKeyConstraint(["token_id"], ["token_registry.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("user_id", "token_id"),
    )
    op.create_table(
        "wallets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("chain", sa.Text(), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("added_via", sa.Text(), nullable=True),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_synced_block", sa.BigInteger(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint("chain IN ('lemonchain','bsc')", name="ck_wallets_chain"),
        sa.CheckConstraint(
            "role IN ('vest','live','stake','nft','cold','bridge','other')", name="ck_wallets_role"
        ),
        sa.CheckConstraint("address = lower(address)", name="ck_wallets_address_lowercase"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "chain", "address", name="uq_wallets_user_chain_address"),
    )
    op.create_table(
        "wallet_entity_assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("wallet_id", sa.Uuid(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("classification", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "classification IN ('initial-assignment','capital-contribution','sale','gift','loan','reassignment')",
            name="ck_wea_classification",
        ),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallets.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_wea_wallet_current",
        "wallet_entity_assignments",
        ["wallet_id"],
        unique=True,
        postgresql_where=sa.text("effective_to IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_wea_wallet_current",
        table_name="wallet_entity_assignments",
        postgresql_where=sa.text("effective_to IS NULL"),
    )
    op.drop_table("wallet_entity_assignments")
    op.drop_table("wallets")
    op.drop_table("user_token_classifications")
    op.drop_table("entities")
    op.drop_table("users")
    op.drop_table("token_registry")
    # ### end Alembic commands ###
